# mysql 数据库连接配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowUrlInLocalInfile=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
# 设置应用启动时 jpa 更新表结构
    jpa:
        generate-ddl: true
        show-sql: true